GULP = $(PWD)/node_modules/.bin/gulp
KARMA = $(PWD)/node_modules/.bin/karma

run:
	  $(GULP) run

clean:
	  $(GULP) clean

build:
		$(GULP) build

watch:
		$(GULP) watch

test:
		$(KARMA) start

.PHONY: run clean build test
