GULP = $(PWD)/node_modules/.bin/gulp
KARMA = $(PWD)/node_modules/.bin/karma

run:
	  $(GULP) run

clean:
	  $(GULP) clean

build:
		$(GULP) build

devbuild:
		$(GULP) dev-build

test:
		$(KARMA) start

.PHONY: run clean build test dev-build
